[package]
name = "xlfr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
calamine = "0.25.0"
pyo3 = { version = "0.22.1", features = ["extension-module"] }